name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    paths:
      - "make-me-impl/**"

defaults:
  run:
    working-directory: make-me-impl

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        run: rustup update stable # Ensure Rust is installed and updated

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose

      - name: Check for test failures
        run: |
          if [ -n "$(cargo test --verbose 2>&1 | grep "thread 'main' panicked")" ]; then
            echo "Tests failed"
            exit 1
          fi

      # - name: Check for clippy warnings
      #   run: cargo clippy -- -D warnings

      - name: Check for formatting errors
        run: cargo fmt -- --check

      - name: Check for security vulnerabilities
        run: cargo audit

      - name: Check for outdated dependencies
        run: cargo outdated
